# This file is Copyright (c) 2022 RapidSilicon.
#
# SPDX-License-Identifier: MIT

DUT = dsp
DSP_SIM ?= $(dsp_sim)

all:
	./tests_dsp_unsigned.sh

clean:
	@rm -rf __pycache__ *.lxt *.vvp *.vcd rapidsilicon ../litex_wrapper/__pycache__ dsp dsp_tests_unsigned.log