# This file is Copyright (c) 2022 RapidSilicon.
#
# SPDX-License-Identifier: MIT

all:
	./test_axil_ethernet.py

clear:
	@rm -rf build firmware/crt0.d firmware/crt0.o
	@rm -rf firmware/ethernet.d firmware/ethernet.o
	@rm -rf firmware/firmware.bin firmware/firmware.elf
	@rm -rf firmware/firmware.elf.map firmware/main.d
	@rm -rf firmware/main.o ../../../../lib/__pycache__/
	@rm -rf ../__pycache__/ ../rapidsilicon