// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : reset_release_wrapper.v
// Device     : gemini
// LiteX sha1 : 611b84cc
// Date       : 2022-12-13 11:27:11
//------------------------------------------------------------------------------
// This file is Copyright (c) 2022 RapidSilicon
//--------------------------------------------------------------------------------


//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module reset_release_wrapper (
    input  wire          slow_clk,
    input  wire          ext_rst,
    input  wire          cpu_dbg_rst,
    input  wire          pll_lock,
    output wire          cpu_rst,
    output wire          periph_aresetn,
    output wire          interconnect_aresetn,
    output wire          bus_reset,
    output wire          periph_reset
);


//------------------------------------------------------------------------------
// Signals
//------------------------------------------------------------------------------

wire          slow_clk_1;
wire          ext_rst_1;
wire          cpu_dbg_rst_1;
wire          pll_lock_1;
wire          cpu_rst_1;
wire          periph_aresetn_1;
wire          interconnect_aresetn_1;
wire          bus_reset_1;
wire          periph_reset_1;

//------------------------------------------------------------------------------
// Combinatorial Logic
//------------------------------------------------------------------------------

assign slow_clk_1 = slow_clk;
assign ext_rst_1 = ext_rst;
assign cpu_dbg_rst_1 = cpu_dbg_rst;
assign pll_lock_1 = pll_lock;
assign cpu_rst = cpu_rst_1;
assign periph_aresetn = periph_aresetn_1;
assign interconnect_aresetn = interconnect_aresetn_1;
assign bus_reset = bus_reset_1;
assign periph_reset = periph_reset_1;


//------------------------------------------------------------------------------
// Synchronous Logic
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
// Specialized Logic
//------------------------------------------------------------------------------

reset_release #(
	.BUS_RESET(1),
	.EXT_RESET_WIDTH(5),
	.INTERCONNECTS(1),
	.PERIPHERAL_ARESETN(1),
	.PERIPHERAL_RESET(1)
) reset_release (
	.cpu_dbg_rst(cpu_dbg_rst_1),
	.ext_rst(ext_rst_1),
	.pll_lock(pll_lock_1),
	.slow_clk(slow_clk_1),
	.bus_reset(bus_reset_1),
	.cpu_rst(cpu_rst_1),
	.interconnect_aresetn(interconnect_aresetn_1),
	.periph_aresetn(periph_aresetn_1),
	.periph_reset(periph_reset_1)
);

endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2022-12-13 11:27:11.
//------------------------------------------------------------------------------
