// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : io_configurator_v1_0.v
// Device     : 
// LiteX sha1 : --------
// Date       : 2024-11-29 11:11:03
//------------------------------------------------------------------------------
// This file is Copyright (c) 2022 RapidSilicon
//--------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module io_configurator_trans #(
	parameter IP_TYPE 		= "IO",
	parameter IP_VERSION 	= 32'h1, 
	parameter IP_ID 		= 32'h5dbb2c3
)
(
    output wire          IOPAD_SDATA,
    input  wire    [7:0] FABRIC_PDATA_0,
    input  wire          FABRIC_CLK_IN,
    input  wire          FABRIC_DATA_VALID,
    input  wire          FABRIC_OE_IN,
    input  wire          FABRIC_RST,
    input  wire          SEL_DLY,
    input  wire          FABRIC_DLY_LOAD,
    input  wire          FABRIC_DLY_ADJ,
    input  wire          FABRIC_DLY_INCDEC,
    output wire    [5:0] FABRIC_DLY_TAP_VALUE_0
);


//------------------------------------------------------------------------------
// Signals
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
// Combinatorial Logic
//------------------------------------------------------------------------------



//------------------------------------------------------------------------------
// Synchronous Logic
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
// Specialized Logic
//------------------------------------------------------------------------------

DLY_CONFIG_trans #(
	.DATA_RATE("SDR"),
	.DELAY(5'd30),
	.DELAY_TYPE("STATIC"),
	.DIFFERENTIAL_TERMINATION("FALSE"),
	.DLY_LOC(40'b0),
	.DLY_SEL_WIDTH(1'd1),
	.DRIVE_STRENGTH(2'd2),
	.IOSTANDARD("DEFAULT"),
	.IO_TYPE("SINGLE_ENDED"),
	.NUM_DLY(1'd1),
	.PLL_DIV(1'd1),
	.PLL_MULT(7'd80),
	.SLEW_RATE("SLOW"),
	.WEAK_KEEPER("NONE"),
	.WIDTH(4'd8)
) DLY_CONFIG_trans (
	.DATA_VALID(FABRIC_DATA_VALID),
	.DLY_ADJ(FABRIC_DLY_ADJ),
	.DLY_INCDEC(FABRIC_DLY_INCDEC),
	.DLY_LOAD(FABRIC_DLY_LOAD),
	.FAB_CLK_IN(FABRIC_CLK_IN),
	.OE_IN(FABRIC_OE_IN),
	.PDATA_IN({FABRIC_PDATA_0}),
	.RESET(FABRIC_RST),
	.SEL_DLY(SEL_DLY),
	.DELAY_TAP_VALUE({FABRIC_DLY_TAP_VALUE_0}),
	.SDATA_OUT(IOPAD_SDATA)
);

endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2024-11-29 11:11:03.
//------------------------------------------------------------------------------
