///////////////////////////////////////////////////////
//  gemini_pss.v
//  Copyright (c) 2023 Rapid Silicon
//  All Right Reserved.
///////////////////////////////////////////////////////

`timescale 1 ps / 1 ps 

module gemini_pss (
	//Slave AHB3 Interface 0
	FPGA_AHB_S0_HADDR,
	FPGA_AHB_S0_HBURST,
	FPGA_AHB_S0_HMASTLOCK,
	FPGA_AHB_S0_HPROT,
	FPGA_AHB_S0_HRDATA,
	FPGA_AHB_S0_HREADY,
	FPGA_AHB_S0_HRESP,
	FPGA_AHB_S0_HSEL,
	FPGA_AHB_S0_HSIZE,
	FPGA_AHB_S0_HTRANS,
	FPGA_AHB_S0_HWBE,
	FPGA_AHB_S0_HWDATA,
	FPGA_AHB_S0_HWRITE,
	FPGA_AHB_S0_RST_N,

	//Master AXI4 Interface 0
	FPGA_AXI_M0_AR_ADDR,
	FPGA_AXI_M0_AR_BURST,
	FPGA_AXI_M0_AR_CACHE,
	FPGA_AXI_M0_AR_ID,
	FPGA_AXI_M0_AR_LEN,
	FPGA_AXI_M0_AR_LOCK,
	FPGA_AXI_M0_AR_PROT,
	FPGA_AXI_M0_AR_READY,
	FPGA_AXI_M0_AR_SIZE,
	FPGA_AXI_M0_AR_VALID,
	FPGA_AXI_M0_AW_ADDR,
	FPGA_AXI_M0_AW_BURST,
	FPGA_AXI_M0_AW_CACHE,
	FPGA_AXI_M0_AW_ID,
	FPGA_AXI_M0_AW_LEN,
	FPGA_AXI_M0_AW_LOCK,
	FPGA_AXI_M0_AW_PROT,
	FPGA_AXI_M0_AW_READY,
	FPGA_AXI_M0_AW_SIZE,
	FPGA_AXI_M0_AW_VALID,
	FPGA_AXI_M0_B_ID,
	FPGA_AXI_M0_B_READY,
	FPGA_AXI_M0_B_RESP,
	FPGA_AXI_M0_B_VALID,
	FPGA_AXI_M0_R_DATA,
	FPGA_AXI_M0_R_ID,
	FPGA_AXI_M0_R_LAST,
	FPGA_AXI_M0_R_READY,
	FPGA_AXI_M0_R_RESP,
	FPGA_AXI_M0_R_VALID,
	FPGA_AXI_M0_W_DATA,
	FPGA_AXI_M0_W_LAST,
	FPGA_AXI_M0_W_READY,
	FPGA_AXI_M0_W_STRB,
	FPGA_AXI_M0_W_VALID,
	FPGA_AXI_M0_RST_N,

	//Master AXI4 Interface 1
	FPGA_AXI_M1_AR_ADDR,
	FPGA_AXI_M1_AR_BURST,
	FPGA_AXI_M1_AR_CACHE,
	FPGA_AXI_M1_AR_ID,
	FPGA_AXI_M1_AR_LEN,
	FPGA_AXI_M1_AR_LOCK,
	FPGA_AXI_M1_AR_PROT,
	FPGA_AXI_M1_AR_READY,
	FPGA_AXI_M1_AR_SIZE,
	FPGA_AXI_M1_AR_VALID,
	FPGA_AXI_M1_AW_ADDR,
	FPGA_AXI_M1_AW_BURST,
	FPGA_AXI_M1_AW_CACHE,
	FPGA_AXI_M1_AW_ID,
	FPGA_AXI_M1_AW_LEN,
	FPGA_AXI_M1_AW_LOCK,
	FPGA_AXI_M1_AW_PROT,
	FPGA_AXI_M1_AW_READY,
	FPGA_AXI_M1_AW_SIZE,
	FPGA_AXI_M1_AW_VALID,
	FPGA_AXI_M1_B_ID,
	FPGA_AXI_M1_B_READY,
	FPGA_AXI_M1_B_RESP,
	FPGA_AXI_M1_B_VALID,
	FPGA_AXI_M1_R_DATA,
	FPGA_AXI_M1_R_ID,
	FPGA_AXI_M1_R_LAST,
	FPGA_AXI_M1_R_READY,
	FPGA_AXI_M1_R_RESP,
	FPGA_AXI_M1_R_VALID,
	FPGA_AXI_M1_W_DATA,
	FPGA_AXI_M1_W_LAST,
	FPGA_AXI_M1_W_READY,
	FPGA_AXI_M1_W_STRB,
	FPGA_AXI_M1_W_VALID,
	FPGA_AXI_M1_RST_N,

	//FPGA-to-SoC Interrupts
	IRQ_F2A,
	IRQ_F2A_RST_N,

	//SoC-to-FPGA Interrupts
	IRQ_A2F,
	IRQ_A2F_RST_N,

	//SoC-to-FPGA DMA Signals
	DMA_A2F,
	//FPGA-to-Soc DMA Signals
	DMA_F2A	
);

  
//Slave AHB3 Interface 0
input	[31:0]	FPGA_AHB_S0_HADDR;
input	[2:0]	FPGA_AHB_S0_HBURST;
input			FPGA_AHB_S0_HMASTLOCK;
output	[3:0]	FPGA_AHB_S0_HPROT;
output	[31:0]	FPGA_AHB_S0_HRDATA;
output			FPGA_AHB_S0_HREADY;
output			FPGA_AHB_S0_HRESP;
input			FPGA_AHB_S0_HSEL;
input	[2:0]	FPGA_AHB_S0_HSIZE;
input	[1:0]	FPGA_AHB_S0_HTRANS;
input	[3:0]	FPGA_AHB_S0_HWBE;
input	[31:0]	FPGA_AHB_S0_HWDATA;
input			FPGA_AHB_S0_HWRITE;
input			FPGA_AHB_S0_RST_N;

//Master AXI4 Interface 0
output	[31:0]	FPGA_AXI_M0_AR_ADDR;
output	[1:0]	FPGA_AXI_M0_AR_BURST;
output	[3:0]	FPGA_AXI_M0_AR_CACHE;
output	[3:0]	FPGA_AXI_M0_AR_ID;
output	[2:0]	FPGA_AXI_M0_AR_LEN;
output			FPGA_AXI_M0_AR_LOCK;
output	[2:0]	FPGA_AXI_M0_AR_PROT;
input			FPGA_AXI_M0_AR_READY;
output	[2:0]	FPGA_AXI_M0_AR_SIZE;
output			FPGA_AXI_M0_AR_VALID;
output	[31:0]	FPGA_AXI_M0_AW_ADDR;
output	[1:0]	FPGA_AXI_M0_AW_BURST;
output	[3:0]	FPGA_AXI_M0_AW_CACHE;
output	[3:0]	FPGA_AXI_M0_AW_ID;
output	[2:0]	FPGA_AXI_M0_AW_LEN;
output			FPGA_AXI_M0_AW_LOCK;
output	[2:0]	FPGA_AXI_M0_AW_PROT;
input			FPGA_AXI_M0_AW_READY;
output	[2:0]	FPGA_AXI_M0_AW_SIZE;
output			FPGA_AXI_M0_AW_VALID;
input	[3:0]	FPGA_AXI_M0_B_ID;
output			FPGA_AXI_M0_B_READY;
input	[1:0]	FPGA_AXI_M0_B_RESP;
input			FPGA_AXI_M0_B_VALID;
input	[63:0]	FPGA_AXI_M0_R_DATA;
input	[3:0]	FPGA_AXI_M0_R_ID;
input			FPGA_AXI_M0_R_LAST;
output			FPGA_AXI_M0_R_READY;
input	[1:0]	FPGA_AXI_M0_R_RESP;
input			FPGA_AXI_M0_R_VALID;
output	[63:0]	FPGA_AXI_M0_W_DATA;
output			FPGA_AXI_M0_W_LAST;
output			FPGA_AXI_M0_W_READY;
output	[7:0]	FPGA_AXI_M0_W_STRB;
output			FPGA_AXI_M0_W_VALID;
input			FPGA_AXI_M0_RST_N;

//Master AXI4 Interface 1
output	[31:0]	FPGA_AXI_M1_AR_ADDR;
output	[1:0]	FPGA_AXI_M1_AR_BURST;
output	[3:0]	FPGA_AXI_M1_AR_CACHE;
output	[3:0]	FPGA_AXI_M1_AR_ID;
output	[2:0]	FPGA_AXI_M1_AR_LEN;
output			FPGA_AXI_M1_AR_LOCK;
output	[2:0]	FPGA_AXI_M1_AR_PROT;
input			FPGA_AXI_M1_AR_READY;
output	[2:0]	FPGA_AXI_M1_AR_SIZE;
output			FPGA_AXI_M1_AR_VALID;
output	[31:0]	FPGA_AXI_M1_AW_ADDR;
output	[1:0]	FPGA_AXI_M1_AW_BURST;
output	[3:0]	FPGA_AXI_M1_AW_CACHE;
output	[3:0]	FPGA_AXI_M1_AW_ID;
output	[2:0]	FPGA_AXI_M1_AW_LEN;
output			FPGA_AXI_M1_AW_LOCK;
output	[2:0]	FPGA_AXI_M1_AW_PROT;
input			FPGA_AXI_M1_AW_READY;
output	[2:0]	FPGA_AXI_M1_AW_SIZE;
output			FPGA_AXI_M1_AW_VALID;
input	[3:0]	FPGA_AXI_M1_B_ID;
output			FPGA_AXI_M1_B_READY;
input	[1:0]	FPGA_AXI_M1_B_RESP;
input			FPGA_AXI_M1_B_VALID;
input	[63:0]	FPGA_AXI_M1_R_DATA;
input	[3:0]	FPGA_AXI_M1_R_ID;
input			FPGA_AXI_M1_R_LAST;
output			FPGA_AXI_M1_R_READY;
input	[1:0]	FPGA_AXI_M1_R_RESP;
input			FPGA_AXI_M1_R_VALID;
output	[63:0]	FPGA_AXI_M1_W_DATA;
output			FPGA_AXI_M1_W_LAST;
output			FPGA_AXI_M1_W_READY;
output	[7:0]	FPGA_AXI_M1_W_STRB;
output			FPGA_AXI_M1_W_VALID;
input			FPGA_AXI_M1_RST_N;

//FPGA-to-SoC Interrupts
output	[15:0]	IRQ_F2A;
output			IRQ_F2A_RST_N;

//SoC-to-FPGA Interrupts
input	[15:0]	IRQ_A2F;
input			IRQ_A2F_RST_N;

//SoC-to-FPGA DMA Signals
input	[3:0]	DMA_A2F;
//FPGA-to-Soc DMA Signals
output	[3:0]	DMA_F2A;

endmodule