 
// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : ethernet_mac_v1_0.v
// Device     : virgo
// LiteX sha1 : 23d8cd8
// Date       : 2024-05-29 17:58:21
//------------------------------------------------------------------------------
// This file is Copyright (c) 2022 RapidSilicon
//--------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module top #(
	parameter IP_TYPE 		= "EMAC",
	parameter IP_VERSION 	= 32'h1, 
	parameter IP_ID 		= 32'h5d55e95
)
(
    input  wire          gtx_clk_125MHz,
    input  wire          gtx_rst,
    output wire          rx_clk,
    output wire          rx_rst,
    output wire          tx_clk,
    output wire          tx_rst,
    input  wire    [7:0] tx_axis_tdata,
    input  wire          tx_axis_tvalid,
    output wire          tx_axis_tready,
    input  wire          tx_axis_tlast,
    input  wire          tx_axis_tuser,
    output wire    [7:0] rx_axis_tdata,
    output wire          rx_axis_tvalid,
    output wire          rx_axis_tlast,
    output wire          rx_axis_tuser,
    input  wire          gmii_rx_clk,
    input  wire    [7:0] gmii_rxd,
    input  wire          gmii_rx_dv,
    input  wire          gmii_rx_er,
    input  wire          mii_tx_clk,
    output wire          gmii_tx_clk,
    output wire    [7:0] gmii_txd,
    output wire          gmii_tx_en,
    output wire          gmii_tx_er,
    output wire          tx_error_underflow,
    output wire          rx_error_bad_frame,
    output wire          rx_error_bad_fcs,
    output wire    [1:0] speed,
    input  wire    [7:0] cfg_ifg,
    input  wire          cfg_tx_enable,
    input  wire          cfg_rx_enable
);


//------------------------------------------------------------------------------
// Signals
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
// Combinatorial Logic
//------------------------------------------------------------------------------



//------------------------------------------------------------------------------
// Synchronous Logic
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
// Specialized Logic
//------------------------------------------------------------------------------

eth_mac_1g_gmii eth_mac_1g_gmii_inst(
	.cfg_ifg(cfg_ifg),
	.cfg_rx_enable(cfg_rx_enable),
	.cfg_tx_enable(cfg_tx_enable),
	.gmii_rx_clk(gmii_rx_clk),
	.gmii_rx_dv(gmii_rx_dv),
	.gmii_rx_er(gmii_rx_er),
	.gmii_rxd(gmii_rxd),
	.gtx_clk(gtx_clk),
	.gtx_rst(gtx_rst),
	.mii_tx_clk(mii_tx_clk),
	.tx_axis_tdata(tx_axis_tdata),
	.tx_axis_tlast(tx_axis_tlast),
	.tx_axis_tuser(tx_axis_tuser),
	.tx_axis_tvalid(tx_axis_tvalid),
	.gmii_tx_clk(gmii_tx_clk),
	.gmii_tx_en(gmii_tx_en),
	.gmii_tx_er(gmii_tx_er),
	.gmii_txd(gmii_txd),
	.rx_axis_tdata(rx_axis_tdata),
	.rx_axis_tlast(rx_axis_tlast),
	.rx_axis_tuser(rx_axis_tuser),
	.rx_axis_tvalid(rx_axis_tvalid),
	.rx_clk(rx_clk),
	.rx_error_bad_fcs(rx_error_bad_fcs),
	.rx_error_bad_frame(rx_error_bad_frame),
	.rx_rst(rx_rst),
	.speed(speed),
	.tx_axis_tready(tx_axis_tready),
	.tx_clk(tx_clk),
	.tx_error_underflow(tx_error_underflow),
	.tx_rst(tx_rst)
);

endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2024-05-29 17:58:21.
//------------------------------------------------------------------------------
