// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : io_configurator_v1_0.v
// Device     : 
// LiteX sha1 : --------
// Date       : 2024-11-28 18:25:50
//------------------------------------------------------------------------------
// This file is Copyright (c) 2022 RapidSilicon
//--------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module io_configurator #(
	parameter IP_TYPE 		= "IO",
	parameter IP_VERSION 	= 32'h1, 
	parameter IP_ID 		= 32'h5cb6672
)
(
    input  wire          IOPAD_SDATA,
    input  wire          FABRIC_EN,
    input  wire          FABRIC_BITSLIP_ADJ,
    output wire          FABRIC_CLK_OUT,
    output wire          FABRIC_DPA_LOCK,
    output wire          FABRIC_DPA_ERROR,
    output wire          FABRIC_DATA_VALID,
    output wire    [7:0] FABRIC_PDATA_0,
    input  wire          FABRIC_RST,
    input  wire          SEL_DLY,
    input  wire          FABRIC_DLY_LOAD,
    input  wire          FABRIC_DLY_ADJ,
    input  wire          FABRIC_DLY_INCDEC,
    output wire    [5:0] FABRIC_DLY_TAP_VALUE_0
);


//------------------------------------------------------------------------------
// Signals
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
// Combinatorial Logic
//------------------------------------------------------------------------------



//------------------------------------------------------------------------------
// Synchronous Logic
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
// Specialized Logic
//------------------------------------------------------------------------------

DLY_CONFIG #(
	.DATA_RATE("SDR"),
	.DELAY(1'd0),
	.DELAY_TYPE("DYNAMIC"),
	.DIFFERENTIAL_TERMINATION("FALSE"),
	.DLY_LOC(40'h1),
	.DLY_SEL_WIDTH(1'd1),
	.DPA_MODE("NONE"),
	.IOSTANDARD("DEFAULT"),
	.IO_TYPE("SINGLE_ENDED"),
	.NUM_DLY(1'd1),
	.PLL_DIV(1'd1),
	.PLL_MULT(7'd640),
	.WEAK_KEEPER("NONE"),
	.WIDTH(4'd8)
) DLY_CONFIG (
	.BITSLIP_ADJ(FABRIC_BITSLIP_ADJ),
	.DLY_ADJ(FABRIC_DLY_ADJ),
	.DLY_INCDEC(FABRIC_DLY_INCDEC),
	.DLY_LOAD(FABRIC_DLY_LOAD),
	.EN(FABRIC_EN),
	.RESET(FABRIC_RST),
	.SDATA_IN(IOPAD_SDATA),
	.SEL_DLY(SEL_DLY),
	.CLK_OUT(FABRIC_CLK_OUT),
	.DATA_VALID(FABRIC_DATA_VALID),
	.DELAY_TAP_VALUE({FABRIC_DLY_TAP_VALUE_0}),
	.DPA_ERROR(FABRIC_DPA_ERROR),
	.DPA_LOCK(FABRIC_DPA_LOCK),
	.PDATA_OUT({FABRIC_PDATA_0})
);

endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2024-11-28 18:25:50.
//------------------------------------------------------------------------------
